// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "fmt"
	_ "io"
	_ "io/ioutil"
	_ "os"
	_ "reflect"
	_ "sort"
	_ "strings"

	_ "github.com/enescakir/emoji"
	_ "github.com/hashicorp/go-multierror"
	_ "github.com/lixiangzhong/dnsutil"
	_ "github.com/logrusorgru/aurora"
	_ "github.com/spf13/cobra"
	_ "gopkg.in/yaml.v2"
	_ "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	_ "k8s.io/apimachinery/pkg/runtime"
	_ "k8s.io/apimachinery/pkg/runtime/schema"
	_ "k8s.io/cli-runtime/pkg/genericclioptions"
	_ "k8s.io/client-go/dynamic"
	_ "k8s.io/client-go/kubernetes"
	_ "k8s.io/client-go/rest"
	_ "k8s.io/client-go/tools/clientcmd"
	_ "k8s.io/client-go/tools/clientcmd/api"
)
