.PHONY: lint
lint:
	#go fmt ./...
	goimports -l ./
	staticcheck ./...
	errcheck ./...
	golint '-set_exit_status=1' ./...
	go test  ./...


.PHONY: list
list:
	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'
