name: Inspect [linters, tests]

on:
  [workflow_dispatch, push]
jobs:
  go-inspect:
    name: Inspect packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
      - name: go test
        run: go test ./...


